import Head from 'next/head';
import Nav from '../../components/Nav';
import Router from 'next/router';
import peopleJson from '../../libs/people';
import styles from '../../styles/Home.module.css';
import { useRouter } from 'next/router';

export default function Person({
  name,
  about,
  age,
  company,
  eyeColor,
  gender,
  address,
  email,
  balance,
  picture,
}) {
  console.log(peopleJson);
  const router = useRouter();
  const handleOnClick = (guid) => {
    router.push(`/Detail/${guid}`);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>People</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Nav />
        <h1 className={styles.title}>{name}</h1>
        <img src={picture} alt='image off someone' />
        <div>
          <h2>About</h2>
          <p>{about}</p>
          <h3>Info</h3>

          <ul>
            <li>Gender: {gender}</li>
            <li>Eye Color: {eyeColor}</li>
            <li>Age: {age}</li>
            <li>Address: {address}</li>
            <li>Company: {company} </li>
            <li>Cash monay: {balance}</li>
            <li>Email: {email}</li>
          </ul>
        </div>

        <div>
          {peopleJson.map(({ guid, name }) => {
            return (
              <li key={guid} onClick={() => handleOnClick(guid)}>
                {name}
              </li>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Made with ❤</p>
      </footer>
    </div>
  );
}

export async function getStaticPaths() {
  const paths = peopleJson.map((person) => {
    return {
      params: {
        guid: person.guid,
      },
    };
  });
  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const foundPerson = peopleJson.find((person) => person.guid === params.guid);
  return {
    props: foundPerson,
  };
}
