import Head from 'next/head';
import Nav from '../../components/Nav';
import React from 'react';
import peopleJson from '../../libs/people';
import styles from '../../styles/Home.module.css';
import { useRouter } from 'next/router';

export default function Person() {
  const router = useRouter();
  const handleOnClick = (guid) => {
    router.push(`/Detail/${guid}`);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>People</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Nav />
        <h1 className={styles.title}>Detail</h1>

        <div>
          {peopleJson.map(({ guid, name }) => {
            return (
              <li key={guid} onClick={() => handleOnClick(guid)}>
                {name}
              </li>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Made with ❤</p>
      </footer>
    </div>
  );
}
