import { signIn, signOut, useSession } from 'next-auth/react';

import Head from 'next/head';
import Image from 'next/image';
import Nav from '../components/Nav';
import React from 'react';
import Router from 'next/router';
import styles from '../styles/Home.module.css';

function Admin() {
  const { data: session } = useSession();
  if (session) {
    return (
      <div className={styles.container}>
        <Head>
          <title>People</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main className={styles.main}>
          <div>
            <Nav />
          </div>
          <h1 className='text-3xl'>Admin</h1>
          <p>You are admin, happy now?</p>
        </main>
      </div>
    );
  } else {
    return (
      <div className={styles.container}>
        <Head>
          <title>People</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main className={styles.main}>
          <div>
            <Nav />
          </div>
          <h1>THE FUCK YOU DOING HERE?!</h1>
          <h2>You ain&apos;t no damn admin</h2>
          <img
            src='https://www.icegif.com/wp-content/uploads/rickroll-icegif-4.gif'
            alt='get ricked and rolled'
          ></img>
        </main>
      </div>
    );
  }
}

export default Admin;
