import Head from 'next/head';
import Nav from '../components/Nav';
import React from 'react';
import styles from '../styles/Home.module.css';

function Login() {
  return (
    <div className={styles.container}>
      <Head>
        <title>People</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Nav />
      </main>
      Login
    </div>
  );
}

export default Login;
